name: Test

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.9, 3.10]

        steps:
            - uses: actions/checkout@v1

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v1
              with:
                  python-version: ${{ matrix.python }}

            - name: Install Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install poetry

            - name: Install python packages
              run: |
                  poetry install

            # here's the important bit!
            # generate a new project using the cookiecutter template
            # use the default values in cookiecutter.json with --no-input
            # if the directory already exists, overwrite it
            - name: Generate package using cookiecutter
              run: |
                  poetry run cookiecutter . --overwrite-if-exists --no-input
            # now inside the generated project, install dependencies and run tests
            - name: Install python packages (in cookiecutter dir)
              working-directory: example_cli
              run: |
                  poetry install

            - name: Run tests (in cookiecutter dir)
              working-directory: example_cli
              run: |
                  poetry run task tests
