# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.9', '3.10']

        steps:
            - uses: actions/checkout@v2

            -   name: Cache poetry
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.cache/pypoetry
                        ~/.cache/pip
                    key: ${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}


            - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
              uses: actions/setup-python@v2
              with:
                  python-version: {% raw %}${{ matrix.python-version }}{% endraw %}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip poetry
                  poetry config virtualenvs.create false
                  poetry install --no-interaction

            - name: Lint with flake8
              run: |
                  flake8 {{cookiecutter.project_slug}}/ tests/

            - name: Lint with mypy
              run: |
                  mypy --config-file pyproject.toml

            - name: Lint with black
              run: |
                black --config=pyproject.toml --check {{cookiecutter.project_slug}}/ tests/

            - name: Test with pytest
              run: |
                  pytest --no-cov-on-fail --cov {{cookiecutter.project_slug}}/ --cov tests/
